### PR TITLE
Fix LifoQueue's and PriorityQueue's put() and task_done().

### LINKED ISSUE #235: LifoQueue and PriorityQueue's put don't increment unfinished tasks.
I caused this bug when I merged JoinableQueue into Queue. Their "join" methods return immediately, even if items have been put and no one has called task_done.

### PR DESCRIPTION
**Pull request by ajdavis**
Fixes #235.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Thanks, looks good!

**Comment by gvanrossum** [comment]
Whoa, I thought you had run the tests. When I do "make test" I get the following message in the logs, which wasn't there before:
```
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<BaseSelectorEventLoop._accept_connection2() running at /Users/guido/src/asyncio/asyncio/selector_events.py:227> wait_for=<Future finished exception=RuntimeError('Event loop is closed',)>>
```
Worse, when I patch this into the 3.4 branch I get real errors:
```
======================================================================
ERROR: test_format (test.test_asyncio.test_queues._QueueJoinTestBase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/guido/src/cpython34/Lib/test/test_asyncio/test_queues.py", line 470, in test_format
    q = self.q_class(loop=self.loop)
TypeError: 'NoneType' object is not callable

======================================================================
ERROR: test_join_empty_queue (test.test_asyncio.test_queues._QueueJoinTestBase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/guido/src/cpython34/Lib/test/test_asyncio/test_queues.py", line 457, in test_join_empty_queue
    q = self.q_class(loop=self.loop)
TypeError: 'NoneType' object is not callable

======================================================================
ERROR: test_task_done (test.test_asyncio.test_queues._QueueJoinTestBase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/guido/src/cpython34/Lib/test/test_asyncio/test_queues.py", line 420, in test_task_done
    q = self.q_class(loop=self.loop)
TypeError: 'NoneType' object is not callable

======================================================================
ERROR: test_task_done_underflow (test.test_asyncio.test_queues._QueueJoinTestBase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/guido/src/cpython34/Lib/test/test_asyncio/test_queues.py", line 416, in test_task_done_underflow
    q = self.q_class(loop=self.loop)
TypeError: 'NoneType' object is not callable

----------------------------------------------------------------------
```
It looks like the CPython test runner is confused by your class structure and runs the tests in the base class. I'll leave this as is in the asyncio repo but I would like to see both of these issues addressed ASAP!

**Comment by gvanrossum** [comment]
PS. The first error is here:
```
test_create_server_ssl_verify_failed (test_events.PollEventLoopTests) ... ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<BaseSelectorEventLoop._accept_connection2() running at /Users/guido/src/asyncio/asyncio/selector_events.py:227> wait_for=<Future finished exception=RuntimeError('Event loop is closed',)>>
ok
```

**Comment by ajdavis** [comment]
Sorry, "make test" passes for me without the pending-task warning so I thought everything was ok. I've submitted https://github.com/python/asyncio/pull/237 to fix the issue with CPython's test runner.

**Pull request merged**
