### PR TITLE
Make sure BaseException is re-raised in SSLProtocol

### PR DESCRIPTION
**Pull request by 1st1**

### CODE REVIEW

**Comment by gvanrossum** [comment]
Is there a bug describing the need for this fix?

**Comment by 1st1** [comment]
There is no bug. I was reviewing ``sslproto.py`` code while investigating how to implement start_tls, and this particular spot seemed wrong to my eyes. If the execution is stuck somewhere in ``_process_write_backlog`` (and it's a lot of code involved there), it will take two SystemExits or KeyboardInterrupts to about the execution of the loop.

**Comment by gvanrossum** [comment]
OK, LGTM.

**Comment by 1st1** [comment]
Committed in f57cfc623ad.

**Pull request closed without merging**
