### PR TITLE
Fixes Issue23812: asyncio.Queue task cancellation leads to item being lost

### PR DESCRIPTION
**Pull request by gjcarneiro**
asyncio.Queue.put_nowait(), followed get() task cancellation leads to item being
lost.  See http://bugs.python.org/issue23812

### CODE REVIEW

**Comment by 1st1** [comment]
@gjcarneiro Hi Gustavo, thanks for the PR. I've left a few comments there, please take a look.

Overall, I like the patch, let's get this fixed finally.

**Comment by gjcarneiro** [comment]
@1st1 thanks for the review!  The new commit should address those issues.  Cheers.

**Comment by 1st1** [comment]
@gjcarneiro Thanks, Gustavo! LGTM.

@gvanrossum @haypo I'm going to commit Gustavo's patch soon, unless you guys want to review it too.

**Comment by gvanrossum** [comment]
I don't feel the need to review.

**Comment by 1st1** [comment]
Merged. Thanks, @gjcarneiro.

**Pull request closed without merging**
