### PR TITLE
Implement Timeout class

### PR DESCRIPTION
**Pull request by asvetlov**
@gvanrossum @1st1 please review

### CODE REVIEW

**Comment by gvanrossum** [comment]
I'm curious -- perhaps the name should not be capitalized? Several classes in contextlib.py aren't capitalized either (closing redirect_stdout/stderr, suppress). OTOH ExitStack *is* capitalized. I wonder if that's because ExitStack actually has an API besides `__enter__` and `__exit__`. Since your Timeout has no additional public API, perhaps it should be named timeout()?

**Comment by asvetlov** [comment]
Agree with lower cased name.
I can even add context manager support to `wait_for()`:
```
with asyncio.wait_for(1.5, loop=loop):
     yield from coro()
```
but really don't like this approach: it changes type of returned value depending on passed arguments.

**Comment by gvanrossum** [comment]
Yeah, let's make it asyncio.timeout(), but let's not overload wait_for().
Maybe timeout() should be a function that returns a class instance (to
prevent people from trying to subclass or type-check it).

**Comment by asvetlov** [comment]
Moved `Timeout` class to `timeout()` factory function.
I really doubt that people will use `Timeout` for subclassing or type checking but prefer stronger solution until we have a use case for introducing a class as public API.
We can get rid of the factory function later anyway.

**Comment by 1st1** [comment]
LGTM

**Comment by gvanrossum** [comment]
Yes, looks good. Andrew, can you commit this yourself? It needs to be merged into Python 3.4, 3.5, 3.6. It would also be nice to have a Misc/NEWS item and some docs...

**Comment by asvetlov** [comment]
On my way

**Comment by asvetlov** [comment]
Done

**Comment by gvanrossum** [comment]
Thanks!

**Comment by AndreLouisCaron** [comment]
Was this ever merged back into the official `asyncio` module?  I'm using Python 3.5.1 and `from asyncio import timeout` raises an `ImportError`...

**Comment by 1st1** [comment]
@AndreLouisCaron `asyncio.timeout()` was supposed to be a new feature in `3.5.2`, but we decided that its design has to be tweaked. I think we'll finally have it in 3.6.

**Comment by AndreLouisCaron** [comment]
OK thanks!

Out of curiosity, what needs to be changed?  One thing that strikes me as odd in the interface is that explicitly raising a `CancelledError` translates into a `TimeoutError` even if the task didn't time out.  I would expect that to go through (although I assume this will make the implementation trickier).

**Comment by 1st1** [comment]
There are some concerns about interoperability with other frameworks, read this email thread: https://mail.python.org/pipermail/async-sig/2016-June/000045.html

Maybe we'll also make it use the `async with` statement (instead of plain `with`).

As for CancelledError/TimeoutError -- I think that `asyncio.timeout()` behaved in exactly the same way as `asyncio.wait` -- throwing `CancelledError` to stop things, and propagating `TimeoutError` back to the calling coroutine.

**Comment by AndreLouisCaron** [comment]
OK thanks!  I have some related questions, but I guess I'll take those to the mailing list.

**Comment by coxley** [comment]
Absent from 3.6 -- are there any further plans for this?

**Comment by 1st1** [comment]
@coxley Thanks for bringing this issue up.  I'll be working on a PEP regarding new APIs for asyncio in 3.7 soon. Will likely include `asyncio.timeout` in it.

**Pull request merged**
