### PR TITLE
Make Tasks check if Futures are attached to the same event loop

### PR DESCRIPTION
**Pull request by 1st1**

### CODE REVIEW

**Comment by gvanrossum** [comment]
LGTM, but let's wait until the OP gives it a thumbs-up. Thanks for the quick fix!

**Comment by vxgmichel** [comment]
It's fine with me, thanks!

**Comment by 1st1** [comment]
BTW, there is no way to do the check if the future already has the result.  So the exception will only be raised for futures without results/exceptions set.

**Comment by gvanrossum** [comment]
That's OK, those futures are harmless. Go ahead and merge.

--Guido (mobile)

**Comment by 1st1** [comment]
Merged. Thanks!

**Pull request merged**
